version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

nfpms:
  - vendor: Sean Molenaar
    maintainer: 'Sean Molenaar <sean@seanmolenaar.eu>'
    formats:
      - deb
      - rpm
    replaces:
      - resque-web
    bindir: /usr/bin

    contents:
      - src: pkg/linux/resque-inspector.service
        dst: /etc/systemd/system/
        type: config

      - src: /etc/systemd/system/resque-inspector.service
        dst: /etc/systemd/system/resque-web.service
        type: "symlink"
    rpm:
      compression: lzma
      # Prefixes for relocatable packages.
      prefixes:
        - /usr/bin
dockers:
  - dockerfile: Containerfile
    image_templates:
      - "ghcr.io/smillerdev/{{.ProjectName}}:{{ .Tag }}"
      - "ghcr.io/smillerdev/{{.ProjectName}}:latest"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"