version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - curl --output server/css/pico.min.css https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

nfpms:
  - vendor: Sean Molenaar
    maintainer: 'Sean Molenaar <sean@seanmolenaar.eu>'
    formats:
      - deb
      - rpm
    replaces:
      - resque-web
    bindir: /usr/bin

    contents:
      - src: pkg/linux/resque-inspector.service
        dst: /etc/systemd/system/
        type: config

      - src: pkg/linux/service.env.default
        dst: /etc/resque-inspector/service.env
        type: config

      - src: /etc/systemd/system/resque-inspector.service
        dst: /etc/systemd/system/resque-web.service
        type: "symlink"
    rpm:
      compression: lzma
      # Prefixes for relocatable packages.
      prefixes:
        - /usr/bin
dockers_v2:
  - images:
      - "ghcr.io/smillerdev/{{.ProjectName}}"
    tags:
      - "{{ .Version }}"
      - "latest"
    labels:
      "org.opencontainers.image.description": "Resque Inspector queue manager"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    dockerfile: Containerfile

checksum:
  name_template: "checksums.txt"