version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

nfpms:
  - vendor: Sean Molenaar
    maintainer: 'Sean Molenaar <sean@seanmolenaar.eu>'
    formats:
      - deb
      - rpm
    replaces:
      - resque-web
    bindir: /usr/bin

    contents:
      - src: pkg/linux/resque-inspector.service
        dst: /etc/systemd/system/
        type: config

      - src: /etc/systemd/system/resque-inspector.service
        dst: /etc/systemd/system/resque-web.service
        type: "symlink"
    rpm:
      compression: lzma
      # Prefixes for relocatable packages.
      prefixes:
        - /usr/bin
dockers:
  - image_templates:
      - "ghcr.io/smillerdev/{{.ProjectName}}:{{ .Version }}-amd64"
      - "ghcr.io/smillerdev/{{.ProjectName}}:latest-amd64"
    use: buildx
    dockerfile: Containerfile
    skip_push: true
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
  - image_templates:
      - "ghcr.io/smillerdev/{{.ProjectName}}:{{ .Version }}-arm64v8"
      - "ghcr.io/smillerdev/{{.ProjectName}}:latest-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Containerfile
    skip_push: true
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

docker_manifests:
  - name_template: "ghcr.io/smillerdev/{{.ProjectName}}:{{ .Version }}"
    image_templates:
      - "ghcr.io/smillerdev/{{.ProjectName}}:{{ .Version }}-amd64"
      - "ghcr.io/smillerdev/{{.ProjectName}}:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/smillerdev/{{.ProjectName}}:latest"
    image_templates:
      - "ghcr.io/smillerdev/{{.ProjectName}}:latest-amd64"
      - "ghcr.io/smillerdev/{{.ProjectName}}:latest-arm64v8"

checksum:
  name_template: "checksums.txt"