# builder
FROM goreleaser/goreleaser:latest AS builder

WORKDIR /build

COPY . .

RUN goreleaser build --single-target --clean

# Create a production stage to run the application binary
FROM scratch AS production

WORKDIR /app
COPY --from=builder /build/dist/resque-inspector*/resque-inspector ./

EXPOSE 5678
HEALTHCHECK CMD ["/app/resque-inspector", "health"]
CMD ["/app/resque-inspector", "serve"]