name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version: '1.24'

    - name: Build
      run: make build

    - name: Test
      run: go test -v resque-inspector
